### ISSUE TITLE
Overlapping installation docs

### ISSUE THREAD

**Issue by j-woz** [JDACS4C-IMPROVE/docs#33]
There seems to be some overlap between:

quickstart-setup-basic-environment
quickstart-hpo-prerequisites

Is this intentional?

**Comment by wilke** [comment]
No, just evolutional.

Tom will be delete quickstart-hpo-prerequisites

On Sep 13, 2023, at 2:40 PM, Justin M Wozniak ***@***.***> wrote:



There seems to be some overlap between:

quickstart-setup-basic-environment
quickstart-hpo-prerequisites

Is this intentional?

**Comment by j-woz** [comment]
Ok.
